### ISSUE TITLE
Files are not shown on Ubuntu 22.04 / ilia0.11.6-jammy-1

### ISSUE THREAD

**Issue by golmanosocks** [regolith-linux/ilia#22]
when starting the files function via terminal _ilia -p files,_ the following error appears
`
>Gtk-Message: Failed to load module "xapp-gtk3-module"
>Unknown page type: files
>No page loaded, exiting
`

**Comment by kgilmer** [comment]
Hi, if you're looking for the file search dialog it's page name is `tracker`.  See all pages like this:

```
~$ ilia -h
Usage: ilia [-t stylesheet] [-n] [-a] [-p page]

pages:
	'apps' - launch desktop applications (default)
	'terminal' - launch a terminal command
	'notifications' - launch notifications manager
	'keybindings' - launch keybindings viewer
	'textlist' - select an item from a specified list
	'windows' - navigate to a window
	'tracker' - search for files by content

	-t: specify path to custom stylesheet.

	-n: no custom styles

	-a: load all pages
```

**Comment by golmanosocks** [comment]
Dear @kgilmer, 
thanks a lot for the quick response. Unfortunately even with using tracker no files are shown. 
Its basically the same behavior as with #21

**Comment by bacox** [comment]
I have the same problem when using `ilia -p tracker`.
No files shown at all, also no error message.
