### ISSUE TITLE
Incorrect behavior with context menu in ilia search field

### ISSUE THREAD

**Issue by klew** [regolith-linux/ilia#25]
Opening context menu on search field (i.e. by mouse right-click, or by key on keyboard) in ilia is causing that whole ilia window disappears, and only context menu if left open. 
![image](https://user-images.githubusercontent.com/205610/171734940-f77c460c-1d21-4b12-915c-166aaf507b26.png)

**Comment by kgilmer** [comment]
Fixed in beta 3
