### ISSUE TITLE
Slow launch

### ISSUE THREAD

**Issue by 0atman** [regolith-linux/ilia#27]
I'm using the beta version of Regolith, and it takes 1s to open the ilia launcher.

The launcher needs to open instantly, of course. I don't think I need to explain why this is a bug!

Steps to repeat:
I installed regolith beta from deb ppa on new install of 22.04 on a thinkpad X1 Carbon.

I would love to help debug if someone can tell me steps to do so. 

Thank you!

**Comment by kgilmer** [comment]
Hi @0atman , hmm what generation or processor model number is in your computer?  Ilia hasn't really been optimized for startup time yet, but I've found it responsive enough on fairly modest hardware (Intel Core m5-6y57 / 8Gb RAM).  If you run ilia from the commandline do you notice any errors?  You may find better performance by disabling icons.  You can set the icon size to 0 to make this happen.  See the project [readme](https://github.com/regolith-linux/ilia) for details.  Another option is to simply swap back to Rofi if you prefer that.  You simply install the package `regolith-i3-rofi` and `apt` will take care of the rest.  You'll have to supply your own Rofi styles, by setting an Xresource override.  LMK if you'd like more details there.

**Comment by 0atman** [comment]
2019 X1 Carbon, i7 cpu, 16GB ram. No slouch!

Will do some digging as you've suggested

**Comment by 0atman** [comment]
I think that I can't replicate this anymore. Good? Good!
