### ISSUE TITLE
Allow more control on the ordering of items in `textlist`

### ISSUE THREAD

**Issue by kepler** [regolith-linux/ilia#28]
The `textlist` page sorts items by default, which IMHO is unexpected behavior and hinders the ability of using it for custom cases. Taking the example from README description (https://github.com/regolith-linux/ilia#text-list-textlist),
```
ls | ilia -p textlist
```
trying to further customize it with
```
ls -t | ilia -p textlist
```
will produce the end result.

The relevant code line is this: https://github.com/regolith-linux/ilia/blob/main/src/textlist/TextListPage.vala#L72.

Should this be removed, or an additional option added for `textlist` to control for it?

Thanks in advance for looking into it. I can help with a PR, if needed.

**Comment by oliverjenks** [comment]
I'd echo the request for this.  I have a very similar use case for sorting by modified date. Two arguments would be useful, reverse the order, and disable sorting.

**Comment by kepler** [comment]
Thanks for the quick replies. Yes, let's keep it simple and just remove the sorting. It's a one line change (PR: #29, as linked above).
