### ISSUE TITLE
Ilia fails to start GNOME's new Text Editor app

### ISSUE THREAD

**Issue by jc00ke** [regolith-linux/ilia#30]
```
> lsb_release -rd
Description: Ubuntu 22.04 LTS
Release: 22.04

> apt-cache policy gnome-text-editor
gnome-text-editor:
  Installed: 42.1-0ubuntu1
  Candidate: 42.1-0ubuntu1
  Version table:
 *** 42.1-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages
        100 /var/lib/dpkg/status
     42.0-2 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
        500 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
```

I installed the app via `sudo apt install gnome-text-editor` but I'm unable to open it with the `ilia`. I can open the new `gnome-console` app just fine with `ilia`. I can also open `gnome-text-editor` from the terminal with `gtk-launch org.gnome.TextEditor` and it fires right up. I do see the the following output though:

> gtk-launch org.gnome.TextEditor
Gtk-Message: 16:01:19.175: Failed to load module "xapp-gtk3-module"

I'd be happy to help debug, I just need some pointers.

Cross posted from [gnome-text-editor issue](https://bugs.launchpad.net/ubuntu/+source/gnome-text-editor/+bug/1978765).

**Comment by kgilmer** [comment]
Thanks for the detailed bug report @jc00ke !   I'm on the road presently and do not have access to a Jammy environment.  I'll look into this next week.

**Comment by jc00ke** [comment]
No worries, thanks @kgilmer! If there's something I can front run to help debug, let me know.

**Comment by kgilmer** [comment]
When you say "unable to open" do you mean that it does not appear in the app launcher dialog at all, or when you select it, it does not launch?

FWIW I don't think the `xapp-gtk3-module` thing is actually a bug in Ilia, it's some gtk thing and AFAIK it's benign.

**Comment by jc00ke** [comment]
When I select `Text Editor` from `ilia` the app does not start. Sorry, I should have chosen better wording.

**Comment by kgilmer** [comment]
I have reproduced the issue in debian/bookworm.
