### ISSUE TITLE
File search: window doesn't close after selecting result

### ISSUE THREAD

**Issue by carderne** [regolith-linux/ilia#39]
In the other ilia pages (eg 'apps), after hitting `Enter`, the ilia window closes as my app launches.

But with the file search, the ilia window stays open.

I assume this is deliberate but it feels weird and inconsistent with the other behaviour, and I generally only want to "use" one search result.

**Comment by kgilmer** [comment]
It's not deliberate @carderne , just a bug.  I am puzzled why I did not catch this earlier..

**Comment by kgilmer** [comment]
This has been fixed in R2.1 release
