### ISSUE TITLE
Feature-request to make it possible to deactivate icons in ilia -p textlist mode

### ISSUE THREAD

**Issue by fjellvannet** [regolith-linux/ilia#42]
As suggested by @kgilmer a feature-request to disable icons in textlist mode (e.g. -i none). According to the original comment it's currently only possible to deactivate icons for ilia in general, but it would be nice to be able to deactivate it just in only sometimes in textlist-mode as well.

**Comment by kgilmer** [comment]
This was added in Regolith 2.2
