### ISSUE TITLE
Exclude search field as a selectable list item

### ISSUE THREAD

**Issue by morganrowse** [regolith-linux/ilia#44]
Hi as per slack thread
https://regolith-linux.slack.com/archives/CLYDASBFS/p1662966722766889

When opening ilia with a search field, the search field is counted as a list item for keyboard navigation.

This means that an extra keypress is required to navigate filtered items. This is regression from Regolith 1 where Rofi did not count the search field as a navigable list item.

For example
```
mod+space -> Launch App Launcher
search something to filter the results
see you want the second item in the list
press the down key twice to get to the second item
press enter to launch the second item
```

Having the search field not being keyboard navigable would improve the UX for new ilia users and past Rofi users.

Thanks!

**Comment by kgilmer** [comment]
This was fixed in Regolith 2.2
