### ISSUE TITLE
ilia -p textlist keep order of items

### ISSUE THREAD

**Issue by fjellvannet** [regolith-linux/ilia#45]
As I wrote earlier, ilia can be used together with greenclip to form a clipboard-manager in regolith. However I now noticed that `ilia -p textlist` orders the items piped into it alphabetically. This is very unfortunate when it's supposed to be used as a clipboard manager where you'd expect the newest items to appear on top of the list. 

As far as I have studied the options now it's currently not possible prevent ilia from ordering the items alphabetically. Would it be possible to add an option to keep the original ordering of the items piped into `ilia -p textlist`?

**Comment by kgilmer** [comment]
Good idea @fjellvannet

**Comment by kgilmer** [comment]
This is fixed in 2.2:

![image](https://user-images.githubusercontent.com/49683/201298699-18037910-4295-420e-932c-02e9c83d622a.png)
