### ISSUE TITLE
Flatpak applications appear multiple times in the Applications screen

### ISSUE THREAD

**Issue by cjthompson** [regolith-linux/ilia#46]
Ilia shows multiple entries (at least 2, sometimes many more) for applications installed via Flatpak.

Flatpak installed applications usually show up with 2 entries, but at some point something changed and now there are **9** entries for each Flatpak installed application.

I'd post a screenshot but the window disappears when I press PrintScreen.

**Comment by kgilmer** [comment]
@cjthompson ok in the next release of ilia, the search path for apps will be customizable.  So,it should be straightforward to figure out where the redundant app files are and remove that dir from ilia's search path.

**Comment by cjthompson** [comment]
This is fixed in the latest release (though you have to manually configure `app-search-paths` with `dconf`).

**Comment by kgilmer** [comment]
Please LMK if it returns after version `0.12.23`
