### ISSUE TITLE
Aliases?

### ISSUE THREAD

**Issue by pablogrs** [regolith-linux/ilia#52]
Hi, 

In Rofi it was possible to load aliases in a few ways in the configuration. e.g.
`set_from_resource $i3-wm.program.launcher.app i3-wm.program.launcher.app rofi -run-list-command ". ~/.config/i3/aliases.sh" -run-command "/bin/bash -i -c '{cmd}'" -show drun -theme $rofiTheme`

Is there something similar in Ilia? 

Thanks

**Comment by kgilmer** [comment]
Hi, it's not clear to me what "alias" means from the line you've shown.  Generally, `ilia` is less flexible than `rofi`.  One thing it does support is passing a list for selection..  eg `ls / | ilia -p textlist`

**Comment by pablogrs** [comment]
Hi, 
As for alias I mean bash [aliases](https://phoenixnap.com/kb/linux-alias-command) to run commands. 
I am not sure passing a list for selection will work, but I can try to figure it out.

Thanks

**Comment by kgilmer** [comment]
Ah, ok I understand more now thanks @pablogrs .  Do you want to see your bash aliases merged with the commands in the "terminal" page, or do you want your alias as a separate list?  If it's the latter, I was able to get the list w/ this (a bit sloppy): `alias | cut -d' ' -f2 | cut -d'=' -f1 | ilia -p textlist`

**Comment by pablogrs** [comment]
Thanks Ken, I'll try it and come back with the result.
Mostly to be used with i3, Regolith integration.

**Comment by pablogrs** [comment]
Hi @kgilmer I ended up adding the application to the launcher, it doesn't work using aliases.
https://askubuntu.com/questions/224004/how-to-add-programs-to-the-unity-launcher-or-ubuntu-dock
