### ISSUE TITLE
Build Dependencies

### ISSUE THREAD

**Issue by kshitijaucharmal** [regolith-linux/ilia#83]
Can Someone provide **ALL** the build dependencies for ilia? I am trying to port ilia to nix, and it would help to get all the dependencies to maybe search for them in the nix packages.

**Comment by kgilmer** [comment]
Hi, what version of GNOME are you targeting?  The dependencies vary on GTK/GDK version..

**Comment by kshitijaucharmal** [comment]
> Hi, what version of GNOME are you targeting?  The dependencies vary on GTK/GDK version..

I was hoping to start with gtk3. I found this really helpful chart ![regolith_graph.png](https://github.com/regolith-linux/ilia/assets/39955649/187bfa0a-a9b7-46d7-b664-9f01ca850433)

It helped me understand the structure of regolith, 
but it doesn't include ilia

**Comment by kgilmer** [comment]
Ah, this graph is based on the contents of `/debian/control` found in most if not all regolith repos.  Here are the dependencies for the latest version of GTK3 (the library versions of these dev packages): https://github.com/regolith-linux/ilia/blob/ubuntu/impish/debian/control#L9-L13

valac-0.XX-vapi tends to get bumped to new major versions yearly.

**Comment by kshitijaucharmal** [comment]
Thanks :)
