### ISSUE TITLE
Tracker version update

### ISSUE THREAD

**Issue by kshitijaucharmal** [regolith-linux/ilia#84]
I am trying to build ilia on nixos, and found that the build dependency `libtracker-sparql-2.0-dev` is outdated, and has a new version 3.0, [changed 4 years ago](https://gitlab.gnome.org/GNOME/tracker/-/merge_requests/172). 

The nix package for tracker uses the new version. Got this info from this [discussion](https://discourse.nixos.org/t/help-with-building-ilia-from-source/41642/3)

This might help in migration: https://gnome.pages.gitlab.gnome.org/tracker/migrating-2to3.html

**Comment by kshitijaucharmal** [comment]
Never mind, just found that the ubuntu/jammy branch uses the newer version :P

**Comment by kgilmer** [comment]
FYI, this directory represents a "build pipeline" for Regolith packages.  ordering: `experimental` -> `unstable` -> `testing` -> `release_X`

You can see what branches or refs are used to build a given stage of regolith, for example Debian Bookwork is building on the `ubuntu/jammy` branch in the `unstable` stage: https://github.com/regolith-linux/voulage/blob/main/stage/unstable/debian/bookworm/package-model.json#L5

**Comment by kshitijaucharmal** [comment]
Thanks, that helps 😃
